OK. First experiment in rust. I will be aiming at making a procedural
generation library, but I started looking at Rust this week, so the
document will be filled with experiments and distractions as I learn.

Running it:

clipprep ../rust.org | tinyclip -va; pushd procgen; cargo run; popd

* Hello

** Hello World

/*** #file "hello.rs" ***/
fn main() {
    println!("Hello, world!");
}
/*** End of File ***/

Great, compile with rustc and run.

** Hello Cargo

Then

cargo init hello

This yields

/*** #file "hello/src/main.rs" ***/
fn main() {
    println!("Hello, world!");
}
/*** End of File ***/

/*** #file "hello/Cargo.toml" ***/
[package]
name = "hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
/*** End of File ***/

* The first macro

%DefMacro(RustProject,name,%{

/*** #file "%name/src/main.rs" ***/

/*** %name project Contents ***/

fn main() {
  /*** %name  main actions ***/
}
/*** End of File ***/

/*** #file "%name/Cargo.toml" ***/
[package]
name = "%name"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
/*** End of File ***/
%})

** And testing it

%RustProject(hello2)

/*** hello2 main actions ***/
println!("Hello2!");
/*** End of hello2 main actions ***/

* An object hierarchy

** Design

The basic idea is something like this:

There is a tree of objects and sub-objects that is to be procedureally
generated. It is traversed depht first - it need not be available in
memory all the time.

It is generated according to

 1. Object specifications: A given object can be given properties
    (like values, subobjects, guards, hooks, - and specs; see the next
    point).  When traversing any subobjects are expanded according to
    their specifications.
 2. Each object also have a list of spec statements. Those of these
    spec statements that is relevant for the current object are also
    expanded. (Not all are relevant: some spec statements are relevant
    only for subobjects.)

So as a first iteration; what about this featureset:

 * A global collection of top-level object descriptions.
 * An object type. Objects must have a name to identify them. And to
   make this somewhat interesting they must also have subobjects.
 * I should be able to traverse the object hierarchy.

Pseudocode for the envisioned main program:

a = pg_makeObject("A")
b = pg_makeObject("B")
a.addSubObject("B")
a.addSubObject("B")
pg_traverse("A") // Is this better as a debug trait?

This should print something like

A:
  B:
  B:

** The project

%RustProject(procgen)

/*** procgen project Contents ***/
// preamble
use std::fmt;
/*** End of procgen project Contents ***/


** The object type

/*** procgen project Contents ***/
#[derive(Debug)]
struct Object {
  name: String, 
//  subobjects: Vec<usize>,
  specs: Vec<Spec>,
}

impl Object {
  pub fn new(name: String) -> Self {
    Object {
      name: name,
//      subobjects: Vec::new(),
      specs: Vec::new(),
    }
  }
}
  
impl fmt::Display for Object {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}:", self.name)

        // Think about also printing all properties, including
        // expanding all its subobjects? Nah, letting Display start
        // a traversion seems over-the-top.
    }
}

/*** End of procgen project Contents ***/

  pub fn dump_recurse(&self,all_objects: &Classes,prefix: & String){
    let n = &self.name;
    println!("{prefix}{n}:");
    let mut newprefix = prefix.clone();
    newprefix.push_str("  ");

    for i in &self.subobjects {
      all_objects.objects[*i].dump_recurse(all_objects,&newprefix);
    }
    
  }
}


** The global collection of all defined objects?

This is just an array of objects. But I do want it accessed through a
designed interface, so... in rust I use a degenerated struct?

There are two big use-cases for the objects in this collection:

 * After having 'configured the system', that is, created all the
   objects in this collection and filled them in with the relevant
   specs lists, the procedural generation can begin, traversing the
   whole object tree.
 * During this traversial, when a subobject is created, it is cloned
   from the spec here.

The format of the objects in this collection is just objects. But
still... I'll denote /these/ object prototypes 'classes'...

/*** procgen project Contents ***/
#[derive(Debug)]
struct Classes {
  objects: Vec<Object>,
}

impl Classes {
  pub fn new() -> Self {
    Classes {
      objects: Vec::new(),
    }
  }

  pub fn addobject(&mut self,name: &str){
    self.objects.push(Object::new(name.to_string()));
  }
  
  pub fn dump_object_recurse(&self,name: &str){
    let i = self.objects.iter().position(|o| o.name == name).unwrap();
//    let p = "".to_string();
//    self.objects[i].dump_recurse(self,&p);
  }
}

/*** End of procgen project Contents ***/

  pub fn addsubobjectto(&mut self, name: &str,subname: &str){
    // Get the indexes
    let i = self.objects.iter().position(|o| o.name == name).unwrap();
    let j = self.objects.iter().position(|o| o.name == subname).unwrap();
    // println!("Found index: {i} and {j}");
    self.objects[i].subobjects.push(j);
  }


** The main program

/*** procgen main actions ***/
println!("Hello procgen!");

let mut objects = Classes::new();

objects.addobject("Twig");
objects.addobject("Leaf");

// objects.addsubobjectto("Twig","Leaf");
// objects.addsubobjectto("Twig","Leaf");

// println!("{:?}",objects);

objects.dump_object_recurse("Twig");

/*** End of procgen main actions ***/

*** leftovers :noexport:

let mut objects: Vec<Object> = Vec::new();

let mut o = Object::new("A".to_string());
let b = Object::new("B".to_string());

o.subobjects.push(1);
o.subobjects.push(1);

objects.push(o);
objects.push(b);

println!("{:?}",objects[0]);
println!("{}",objects[0]);


** Learning outcomes

 * No default initialization in struct
 * Struct names should be pure camel-case. No prefix. I guess the
   prefix should come in the module or crate.
 * Same with struct members: no subObjects.

Lets live with the dead code warning for the time being.

 * https://dev.to/sgchris/the-debug-vs-display-traits-whats-the-difference-1l58
   Getting to know traits. That will be useful.
 * Unused variables can be prefixed with _ to ignore warning

* Adding properties to objects

** Spec

Properties, values, can be associated with all objects. They behave in
 ... complicated ways:

 * If a property (a property name, a String) in an object is asked for
   its value it is evaluated then and there, /after/ the object has
   been created. Object creation does not set any property values;
   they are evaluated at need.
 * An object definition does not have properties as such. It does
   however have a list of 'Specs' and these specs may specify that a
   property exist and what its value is. 
 * Updates can also be specified.
 * These specs of an object can be specified in more places:
   * Specs can be added to the Generic object in Classes. "Leaf
     Objects have 'color=Green'".
   * A parent object may have Specs that concerns subobjects. "All
     Leaves of this Twig are Brown". The outermost definisions take
     precedence - specs are evaluated from the innermost to the
     outermost. (Though internally in one spec list they are evaluated
     in order.)

Looking closer at a spec

 * Specs may specify values. But also subobjects to be created. Or Guards.
 * They are relevant for this object or some sub-objects.
   * So there is a path element here specifying which subobjects a
     spec is relevant for.
   * They have a name - the property name - a value, subobject
     collection or guard collection.
   * and whatever is necessary to set or modify the given property.

Specs will be an ever-increasing amount. Maybe we can do something
cool with function pointers to increase the functionality and
flexibility even further.

But to start with:

 * Three obvious basic path elements so far: The wildcard, the
   property name and the Object type.
 * Two specs: Creating a subobject and setting a value to some constant.
 
** So... Specs and the Spec union

#+BEGIN_SRC rust
/*** procgen project Contents ***/
#[derive(Debug)]
enum PathElement {
  Any,
  PropertyName {name:String},
  ObjectName {name:String},
}

#[derive(Debug)]
struct Path {
  path_elements: Vec<usize>,
//  property_name: String,  
}

#[derive(Debug)]
enum Spec {
  CreateSubObject {path: Path, name:String, class: String},
  SetValue {path: Path, name:String, value: u32},
}


/*** End of procgen project Contents ***/
#+END_SRC 

 
*** Leftovers :noexport:

 * If a property does not exist in an object, the parent object is
   asked for a value of this property (recurively upwards). - There is
   a kind of inheritance here. (Meh - skip this feature)


* End Matter
