# Main module the user interacts with to generate melodies and rhythms.
import random
import music

# TODO: Implement an automatic way to generate a full melody with rhythms and notes etc...
def generate_melody(key = "c", scale="major", length_bars=4, time_sig="4/4"):

    return


# Generate notes in a melody
def generate_random_notes(length=8):
    """

    Args:
        length (int):  The number of notes in the generated melody.

    Returns:        A list of pitch names representing a melody generated by randomly selecting scale degrees from the chromatic scale and converting them to pitch names based on the key of C major.

    """
    melody = [random.choice(music.SCALES["chromatic"]) for _ in range(length)]
    melody = music.scale_degrees_to_pitch(melody, "c") 
    return melody 


# generate a numbers of bars of random rhythm pattern in a given time signature
def generate_rhythm(bars = 1, keySig = "4/4", values = ["q"]):
    quantitiy, unit = keySig.split('/')
    notesPerBar = int(quantitiy) * (4 / int(unit))
    rhythm  =   []
    tot     =   0
    values  =   rhythm_to_values(values)

    for _ in range(bars):
        tot = 0
        while tot < notesPerBar:
            choices = [v for v in values if tot + v <= notesPerBar]
            val     = random.choice(choices)
            rhythm.append(val)
            tot     += val

    return rhythm

# TODO: Implement rests in the rhythm generation
# Convert rhythm symbols to their corresponding beat values
def rhythm_to_values(rhythm):
    """

    Args:
        rhythm (list): A list of rhythm symbols (e.g., ["q", "e", "s"]) to convert to their corresponding beat values.

    Returns:       A list of beat values corresponding to the input rhythm symbols.

    """
    rhythm_to_val = {
            "l": 16,        # longa
            "b": 8,         # breve
            "w": 4,         # whole note
            "h": 2,         # half note
            "q": 1,         # quarter note
            "e": 0.5,       # eighth note
            "s": 0.25,      # sixteenth note
            "t": 0.125,     # thirty-second note
            "x": 0.0625     # sixty-fourth note
            }
    values = [rhythm_to_val[dur] for dur in rhythm]

    return values


# Generate notes based on intervals
def generate_notes(notes = 4, key = music.build_key("c major")):
    """

    Args:
        notes (int): The number of notes in the generated melody.
        scale (list): The scale to use for generating the melody. Default is the major scale represented by scale_degrees. 

    Returns:       A list of scale degrees representing a melody generated based on random intervals from the given scale.

    """
    intervals   =   [-2, -1, 0, 1, 2] # only 2nds and 3rds for now
    # intervals   =   [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5 ]
    melody      =   []
    current     =   0

    for _ in range(notes):
        val     =   random.choice(intervals)
        current +=  val

        if current < 0:
            current += len(key) 
        if current > len(key) - 1:
            current -= len(key)

        note    =   key[current]
        melody.append(note)

    return melody

