# Main module for generating melodies and rhythms using Melody/Note objects
import random
from core.music import Key, Note, Melody, SCALES

# Generate a random chromatic melody
def generate_random_notes(length=8, key: Key = Key("c", "major")) -> Melody:
    """

    Args:
        length (int): The number of notes in the generated melody.
        key: Key object to decide the key to display the chromatic melody.

    Returns:        A Melody object containing a list of Note objects with randomly generated pitches based on the chromatic scale and the provided key.
        
    """
    # Random scale degrees from chromatic scale
    degrees = [random.choice(SCALES["chromatic"]) for _ in range(length)]
    
    # Create Note objects and convert to pitch
    notes = [Note(degree=int(d.replace("b","").replace("s","") if d[0] in "bs" else int(d)), 
                  pitch=key.degree_to_pitch(d)) for d in degrees]
    
    return Melody(notes = notes, key = key)


# Generate a melody by randomly moving in 2nds and 3rds within the scale
def generate_notes(num_notes=4, key: Key = Key("c", "major")) -> Melody:
    """

    Args:
        num_notes (int): The number of notes in the generated melody.
        key: Key object to decide they key to generate the melody in.

    Returns:       A Melody object containing a list of Note objects representing a melody generated by randomly moving in 2nds and 3rds within the scale defined by the provided key.
        
    """
    intervals = [-2, -1, 0, 1, 2]  # only 2nds and 3rds
    melody_notes = []
    current_idx = 0
    scale = key.get_scale_pitches()

    for _ in range(num_notes):
        val = random.choice(intervals)
        current_idx = (current_idx + val) % len(scale)
        note = Note(degree=current_idx+1, pitch=scale[current_idx])
        melody_notes.append(note)

    return Melody(notes = melody_notes, key = key)



# Helper function to convert rhythm symbols to beat values
def rhythm_to_values(rhythm):
    """

    Args:
        rhythm (list): A list of rhythm symbols (e.g., ["q", "e", "s"]) to convert to their corresponding beat values.

    Returns:      A list of beat values corresponding to the input rhythm symbols.
        
    """
    rhythm_to_val = {
        "l": 16,
        "b": 8,
        "w": 4,
        "h": 2,
        "q": 1,
        "e": 0.5,
        "s": 0.25,
        "t": 0.125,
        "x": 0.0625
    }
    return [rhythm_to_val[dur] for dur in rhythm]


# Generate a rhythm pattern based on the time signature and allowed rhythm values
def generate_rhythm(bars=1, time_sig="4/4", values=["q"]):
    """

    Args:
        bars (int): The number of bars to generate the rhythm for.
        time_sig (str): The time signature to use for generating the rhythm (e.g., "4/4", "3/4", "6/8").
        values (list): A list of rhythm symbols (e.g., ["q", "e", "s"]) to use as the allowed rhythm values for generating the rhythm pattern.

    Returns:
        
    """
    quantity, unit = map(int, time_sig.split("/"))
    notes_per_bar = int(quantity * (4 / unit))
    rhythm = []
    values = rhythm_to_values(values)

    for _ in range(bars):
        tot = 0
        while tot < notes_per_bar:
            choices = [v for v in values if tot + v <= notes_per_bar]
            val = random.choice(choices)
            rhythm.append(val)
            tot += val

    return rhythm
